---
abstract: 'Run command-line sessions to network appliances'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Appliance-Session
requires:
  Cwd: 0
  Data::Dumper: 0
  Getopt::Long: 2.24
  IO::Handle: 0
  IO::Prompt::Tiny: 0
  Moo: 0
  Moo::Role: 0
  MooX::Types::MooseLike::Base: 0
  Net::CLI::Interact: 2.200000
  Sub::Quote: 0
  Term::ANSIColor: 0
  Term::ReadPassword: 0
  Text::Glob: 0
  Text::ParseWords: 0
  Try::Tiny: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-Appliance-Session
  homepage: https://github.com/ollyg/Net-Appliance-Session/wiki
  repository: git://github.com/ollyg/Net-Appliance-Session.git
version: 4.200003
