# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Appliance-Session
version:      1.23
version_from: lib/Net/Appliance/Session.pm
installdirs:  site
requires:
    Class::Accessor:               0.25
    Class::Accessor::Fast::Contained: 0
    Exception::Class:              0
    IO::Pty:                       0
    Net::Appliance::Phrasebook:    1.2
    Net::Telnet:                   0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
